In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3, 4, 5])
print("Array:", array1)
print("Shape:", array1.shape)
print("Data Type:", array1.dtype)

Array: [1 2 3 4 5]
Shape: (5,)
Data Type: int64


In [3]:
array2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array2)
print("Shape:", array2.shape)
print("Data Type:", array2.dtype)

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Data Type: int64


In [8]:
list1 =  [[7, 8, 9], [10, 11, 12]]
array3 = np.array(list1)
print("Array from list:", array3)
print("Shape:", array3.shape)
print("Data Type:", array3.dtype)

Array from list: [[ 7  8  9]
 [10 11 12]]
Shape: (2, 3)
Data Type: int64


In [ ]:
n1 = np.zeros((1,2))
n1

array([[0., 0.],
       [0., 0.]])

In [15]:
n2 = np.ones((2,3))
n2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
n3 = np.full((2,2), 7)
n3

array([[7, 7],
       [7, 7]])

In [ ]:
n4 = np.arange(0, 11, 1.5)
n4

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5])

In [ ]:
n5 = np.random.randint(0,100, size = (3,4)) # For more than 1-D array give size as a tuple
n5

array([[22, 20, 54, 84],
       [22, 83, 96,  9],
       [65, 38, 72, 46]], dtype=int32)

In [ ]:
n6 = np.random.randint(0, 100, 5) # 1-D array give size as a single integer
n6

array([58, 98, 66, 53,  5], dtype=int32)

In [27]:
n7 = np.random.rand(2,3)  # Uniform distribution over [0, 1)
n7

array([[0.39647633, 0.33443565, 0.74076621],
       [0.85538958, 0.29502632, 0.6171967 ]])

In [28]:
n8 = np.random.randn(2,3)  # Standard normal distribution
n8

array([[ 1.23186808, -0.47983559, -0.64074229],
       [ 1.40319635,  0.59616701,  0.50813537]])

In [29]:
n9 = np.linspace(0, 10, 5)  # 5 evenly spaced numbers between 0 and 10
n9

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
n10 = np.eye(4)  # 4x4 Identity matrix
n10

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
n11 = np.empty((2,3))  # Uninitialized array
n11

array([[1.23186808, 0.47983559, 0.64074229],
       [1.40319635, 0.59616701, 0.50813537]])

In [32]:
n12 = np.random.random((2,2))  # Random floats in [0.0, 1.0)
n12

array([[0.89141592, 0.1495525 ],
       [0.01092219, 0.45310444]])

In [ ]:
n13  = np.random.randint(1, 10, size=(3,4))
print ("Original n13:", n13)
n13.shape

Original n13 shape: [[9 7 2 4]
 [9 2 9 5]
 [2 4 7 8]]


(3, 4)

In [ ]:
n13.shape = (4,3) # Reshaping the array
print("Reshaped n13:", n13)
n13 

array([[4, 8, 8],
       [3, 6, 5],
       [2, 8, 6],
       [2, 5, 1]], dtype=int32)

In [40]:
n13.shape = (2,6)
print("Reshaped n13:", n13)

Reshaped n13: [[9 7 2 4 9 2]
 [9 5 2 4 7 8]]


### Joining Arrays
#### VERTICAL STACK |  HORIZONTAL STACK | COLUMN STACK

In [41]:
newarray1 = np.array([1, 2, 3])
newarray2 = np.array([1, 2, 3])
joined_array = np.vstack((newarray1, newarray2))
joined_array

array([[1, 2, 3],
       [1, 2, 3]])

In [46]:
newarray3 = np.array([[1, 2, 3], [4, 5, 6]])
newarray4 = np.array([[7, 8, 9], [10, 11, 12]])
joined_array2 = np.hstack((newarray3, newarray4))
joined_array2

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [47]:
newarray5 = np.array([[1, 2, 3], [4, 5, 6]])
newarray6 = np.array([[7, 8, 9], [10, 11, 12]])
joined_array3 = np.column_stack((newarray5, newarray6))
joined_array3

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### Time:  NUMPY ARRAY ARE FASTER

In [3]:
import time

In [ ]:
SIZE = 1000000

list1 = list(range(SIZE))
list2 = list(range(SIZE))

array1 = np.arange(SIZE)
array2 = np.arange(SIZE)



In [4]:
List_start_time = time.time()
list3 = list1 + list2
List_end_time = time.time()
print("Time taken for list addition:", List_end_time - List_start_time)
Array_start_time = time.time()
array3 = array1 + array2
Array_end_time = time.time()
print("Time taken for array addition:", Array_end_time - Array_start_time)
print("Are the results equal?", np.array_equal(list3, array3))

Time taken for list addition: 7.843971252441406e-05
Time taken for array addition: 0.00040340423583984375
Are the results equal? False


In [7]:
dim_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Number of dimensions:", dim_array.ndim)
print("dtype of the array:", dim_array.dtype)

Number of dimensions: 2
dtype of the array: int64


In [ ]:
# Find SIZE OF ARRAY (NUMBER OF ELEMENTS)
Size_of_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Size of the array:", Size_of_array.size)

Size of the array: 6


In [9]:
# AXIS OF ARRAY
axis_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Axis 0 (columns):", np.sum(axis_array, axis=0)) # Sum along columns
print("Axis 1 (rows):", np.sum(axis_array, axis=1)) # Sum along rows

Axis 0 (columns): [5 7 9]
Axis 1 (rows): [ 6 15]


# SQUARE ROOT AND STANDARD DEVIATION

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:\n", a)
print("SQUARE ROOT of the array:\n", np.sqrt(a))
print("SQUARE of the array:\n", np.square(a))
print("STANDARD DEVIATION of the array:\n", np.std(a))
print("MEAN of the array:\n", np.mean(a))


Original array:
 [[1 2 3]
 [4 5 6]]
SQUARE ROOT of the array:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
SQUARE of the array:
 [[ 1  4  9]
 [16 25 36]]
STANDARD DEVIATION of the array:
 1.707825127659933
MEAN of the array:
 3.5


In [16]:
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[7, 8, 9], [10, 11, 12]])
add = np.add(c, d)
add

array([[ 8, 10, 12],
       [14, 16, 18]])

In [17]:
sub = np.subtract(d, c)
sub

array([[6, 6, 6],
       [6, 6, 6]])

In [18]:
division = np.divide(d, c)
division

array([[7. , 4. , 3. ],
       [2.5, 2.2, 2. ]])

In [19]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
c.ravel()


array([1, 2, 3, 4, 5, 6])