In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3, 4, 5])
print("Array:", array1)
print("Shape:", array1.shape)
print("Data Type:", array1.dtype)

Array: [1 2 3 4 5]
Shape: (5,)
Data Type: int64


In [3]:
array2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array2)
print("Shape:", array2.shape)
print("Data Type:", array2.dtype)

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Data Type: int64


In [8]:
list1 =  [[7, 8, 9], [10, 11, 12]]
array3 = np.array(list1)
print("Array from list:", array3)
print("Shape:", array3.shape)
print("Data Type:", array3.dtype)

Array from list: [[ 7  8  9]
 [10 11 12]]
Shape: (2, 3)
Data Type: int64


In [ ]:
n1 = np.zeros((1,2))
n1

array([[0., 0.],
       [0., 0.]])

In [15]:
n2 = np.ones((2,3))
n2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
n3 = np.full((2,2), 7)
n3

array([[7, 7],
       [7, 7]])

In [ ]:
n4 = np.arange(0, 11, 1.5)
n4

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5])